---
$$ \Large\color{#1a73e8}{\textbf{SwiftFlow App Market Positioning }} $$  $$\large\textbf{Phase 1: Data Cleaning & Preprocessing}$$

---
**Project Metadata:**

*   **Dataset:** Google Play Store Apps (Kaggle)
*   **Author:** Sasi Kiran
*   **Date:** May 2026
*   **Tech Stack:** Python (Pandas, Matplotlib, Seaborn)
---

**Objective:** To perform an initial sanity check on the raw dataset, identify structural anomalies, handle null values, and standardize data types for exploratory data analysis.

### Step 1: Environment Setup & Data Ingestion
Initializing our core analytical toolkit (Pandas, Numpy) and visualization libraries. We are loading the raw Google Play Store dataset to perform our initial structural Sanity Check before any cleaning occurs.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Import data
data = pd.read_csv('/content/googleplaystore.csv')
data.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [2]:
# Check structural health and data types
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  object
 1   Category        10841 non-null  object
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  object
 4   Size            10841 non-null  object
 5   Installs        10841 non-null  object
 6   Type            10840 non-null  object
 7   Price           10841 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10841 non-null  object
 10  Last Updated    10841 non-null  object
 11  Current Ver     10833 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), object(12)
memory usage: 1.1+ MB

### Step 2: Data Transformation & Type Casting

**The Issue:**
Initial inspection reveals that core numerical columns (`Installs`, `Price`, `Size`) are read by Pandas as `object` (strings). This is due to the presence of special formatting characters (e.g., `+`, `,`, `$`, `M`, `k`) and inconsistent text entries (e.g., "Varies with device").

**The Action:**
To perform quantitative analysis for the SwiftFlow launch, we must systematically strip these non-numeric characters and cast the variables to proper numeric data types (integers and floats).

In [3]:
data[data['Installs'] == 'Free']

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.0,3.0M,"1,000+",Free,0,Everyone,NaN,"February 11, 2018",1.0.19,4.0 and up,NaN

In [4]:
# Drop the corrupted row by its index number
data = data.drop(10472)

In [5]:
# Transform Installs column
data['Installs'] = data['Installs'].str.replace('+','',regex = False)
data['Installs'] = data['Installs'].str.replace(',', '', regex= False)

# Convert the column to an integer
data['Installs'] = data['Installs'].astype(int)

In [6]:
# Transform Price column
data['Price'] = data['Price'].str.replace('$','', regex = False)

# Convert the column to Numeric
data['Price'] = data['Price'].astype(float)

In [7]:
data['Size'].unique()

array(['19M', '14M', '8.7M', '25M', '2.8M', '5.6M', '29M', '33M', '3.1M',
       '28M', '12M', '20M', '21M', '37M', '2.7M', '5.5M', '17M', '39M',
       '31M', '4.2M', '7.0M', '23M', '6.0M', '6.1M', '4.6M', '9.2M',
       '5.2M', '11M', '24M', 'Varies with device', '9.4M', '15M', '10M',
       '1.2M', '26M', '8.0M', '7.9M', '56M', '57M', '35M', '54M', '201k',
       '3.6M', '5.7M', '8.6M', '2.4M', '27M', '2.5M', '16M', '3.4M',
       '8.9M', '3.9M', '2.9M', '38M', '32M', '5.4M', '18M', '1.1M',
       '2.2M', '4.5M', '9.8M', '52M', '9.0M', '6.7M', '30M', '2.6M',
       '7.1M', '3.7M', '22M', '7.4M', '6.4M', '3.2M', '8.2M', '9.9M',
       '4.9M', '9.5M', '5.0M', '5.9M', '13M', '73M', '6.8M', '3.5M',
       '4.0M', '2.3M', '7.2M', '2.1M', '42M', '7.3M', '9.1M', '55M',
       '23k', '6.5M', '1.5M', '7.5M', '51M', '41M', '48M', '8.5M', '46M',
       '8.3M', '4.3M', '4.7M', '3.3M', '40M', '7.8M', '8.8M', '6.6M',
       '5.1M', '61M', '66M', '79k', '8.4M', '118k', '44M', '695k', '1.6M',
       '6.2M', '18k', '53M', '1.4M', '3.0M', '5.8M', '3.8M', '9.6M',
       '45M', '63M', '49M', '77M', '4.4M', '4.8M', '70M', '6.9M', '9.3M',
       '10.0M', '8.1M', '36M', '84M', '97M', '2.0M', '1.9M', '1.8M',
       '5.3M', '47M', '556k', '526k', '76M', '7.6M', '59M', '9.7M', '78M',
       '72M', '43M', '7.7M', '6.3M', '334k', '34M', '93M', '65M', '79M',
       '100M', '58M', '50M', '68M', '64M', '67M', '60M', '94M', '232k',
       '99M', '624k', '95M', '8.5k', '41k', '292k', '11k', '80M', '1.7M',
       '74M', '62M', '69M', '75M', '98M', '85M', '82M', '96M', '87M',
       '71M', '86M', '91M', '81M', '92M', '83M', '88M', '704k', '862k',
       '899k', '378k', '266k', '375k', '1.3M', '975k', '980k', '4.1M',
       '89M', '696k', '544k', '525k', '920k', '779k', '853k', '720k',
       '713k', '772k', '318k', '58k', '241k', '196k', '857k', '51k',
       '953k', '865k', '251k', '930k', '540k', '313k', '746k', '203k',
       '26k', '314k', '239k', '371k', '220k', '730k', '756k', '91k',
       '293k', '17k', '74k', '14k', '317k', '78k', '924k', '902k', '818k',
       '81k', '939k', '169k', '45k', '475k', '965k', '90M', '545k', '61k',
       '283k', '655k', '714k', '93k', '872k', '121k', '322k', '1.0M',
       '976k', '172k', '238k', '549k', '206k', '954k', '444k', '717k',
       '210k', '609k', '308k', '705k', '306k', '904k', '473k', '175k',
       '350k', '383k', '454k', '421k', '70k', '812k', '442k', '842k',
       '417k', '412k', '459k', '478k', '335k', '782k', '721k', '430k',
       '429k', '192k', '200k', '460k', '728k', '496k', '816k', '414k',
       '506k', '887k', '613k', '243k', '569k', '778k', '683k', '592k',
       '319k', '186k', '840k', '647k', '191k', '373k', '437k', '598k',
       '716k', '585k', '982k', '222k', '219k', '55k', '948k', '323k',
       '691k', '511k', '951k', '963k', '25k', '554k', '351k', '27k',
       '82k', '208k', '913k', '514k', '551k', '29k', '103k', '898k',
       '743k', '116k', '153k', '209k', '353k', '499k', '173k', '597k',
       '809k', '122k', '411k', '400k', '801k', '787k', '237k', '50k',
       '643k', '986k', '97k', '516k', '837k', '780k', '961k', '269k',
       '20k', '498k', '600k', '749k', '642k', '881k', '72k', '656k',
       '601k', '221k', '228k', '108k', '940k', '176k', '33k', '663k',
       '34k', '942k', '259k', '164k', '458k', '245k', '629k', '28k',
       '288k', '775k', '785k', '636k', '916k', '994k', '309k', '485k',
       '914k', '903k', '608k', '500k', '54k', '562k', '847k', '957k',
       '688k', '811k', '270k', '48k', '329k', '523k', '921k', '874k',
       '981k', '784k', '280k', '24k', '518k', '754k', '892k', '154k',
       '860k', '364k', '387k', '626k', '161k', '879k', '39k', '970k',
       '170k', '141k', '160k', '144k', '143k', '190k', '376k', '193k',
       '246k', '73k', '658k', '992k', '253k', '420k', '404k', '470k',
       '226k', '240k', '89k', '234k', '257k', '861k', '467k', '157k',
       '44k', '676k', '67k', '552k', '885k', '1020k', '582k', '619k'],
      dtype=object)

In [8]:
import numpy as np

def clean_size(size_val):
    if size_val == 'Varies with device':
        return np.nan
    elif size_val[-1] == 'M':
        return float(size_val[:-1]) # Already in Megabytes
    elif size_val[-1] == 'k':
        return float(size_val[:-1]) / 1024 # Convert KB to MB
    else:
        return np.nan # Catch any other weird edge cases

In [9]:
# Apply the function to the Size column
data['Size'] = data['Size'].apply(clean_size)

# Rename the column
data.rename(columns={'Size': 'Size_MB'}, inplace=True)

data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10840 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  object
 4   Size_MB         9145 non-null   float64
 5   Installs        10840 non-null  int64
 6   Type            10839 non-null  object
 7   Price           10840 non-null  float64
 8   Content Rating  10840 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10840 non-null  object
 11  Current Ver     10832 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(3), int64(1), object(9)
memory usage: 1.2+ MB

### Step 3: Duplicate Purge
Removing exact duplicate rows to prevent artificial inflation of popular apps in our downstream analysis.

In [10]:
# Count exact duplicate rows
duplicate_count = data.duplicated().sum()
print(f"Total Duplicated Rows : {duplicate_count}")

Total Duplicated Rows : 483

In [11]:
print("Original Shape :", data.shape)

# Drop Duplicate Rows
data = data.drop_duplicates()

print("Cleaned Shape:", data.shape)

Original Shape : (10840, 13)
Cleaned Shape: (10357, 13)

### Step 4: Null Value Imputation
*   **Minor Categoricals:** Dropping rows with missing `Type`, `Current Ver`, and `Android Ver` (negligible data loss).
*   **Rating:** Imputing missing values using the **Mean** rating of the app's specific `Category`.
*   **Size_MB:** Imputing missing values using the **Median** size of the app's specific `Category` to avoid outlier skew.

In [12]:
# Count null values in every column
print("\n--- Missing Values ---")
print(data.isnull().sum())

--- Missing Values ---
App                  0
Category             0
Rating            1465
Reviews              0
Size_MB           1526
Installs             0
Type                 1
Price                0
Content Rating       0
Genres               0
Last Updated         0
Current Ver          8
Android Ver          2
dtype: int64

In [14]:
# Drop minor categorical nulls
data.dropna(subset=['Type','Current Ver', 'Android Ver'], inplace= True)


# Impute Rating with Category Mean
data['Rating'] = data['Rating'].fillna(
    data.groupby('Category')['Rating'].transform('mean')
)


# Impute Size_MB with Category Median
data['Size_MB'] = data['Size_MB'].fillna(
    data.groupby('Category')['Size_MB'].transform('median')
)

# Verify
print("--- Missing Values After Imputation ---")
print(data.isnull().sum())

--- Missing Values After Imputation ---
App               0
Category          0
Rating            0
Reviews           0
Size_MB           0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

### Step 5: Feature Engineering (Genres)
The raw `Genres` column contains multiple sub-genres separated by semicolons (e.g., 'Puzzle;Brain Games'). To ensure accurate aggregation during EDA, we are engineering a `Primary_Genre` feature that isolates only the root category.

In [22]:
data['Genres'].unique()[:20]

array(['Art & Design', 'Art & Design;Pretend Play',
       'Art & Design;Creativity', 'Art & Design;Action & Adventure',
       'Auto & Vehicles', 'Beauty', 'Books & Reference', 'Business',
       'Comics', 'Comics;Creativity', 'Communication', 'Dating',
       'Education;Education', 'Education', 'Education;Creativity',
       'Education;Music & Video', 'Education;Action & Adventure',
       'Education;Pretend Play', 'Education;Brain Games', 'Entertainment'],
      dtype=object)

In [28]:
# Create the new feature by splitting the string at the semicolon and taking the first item

data['Primary_Genre'] = data['Genres'].str.split(';').str[0]

print("----- OLD VS NEW -----")
print(data[['Genres', 'Primary_Genre']].head(15))

----- OLD VS NEW -----
                       Genres Primary_Genre
0                Art & Design  Art & Design
1   Art & Design;Pretend Play  Art & Design
2                Art & Design  Art & Design
3                Art & Design  Art & Design
4     Art & Design;Creativity  Art & Design
5                Art & Design  Art & Design
6                Art & Design  Art & Design
7                Art & Design  Art & Design
8                Art & Design  Art & Design
9     Art & Design;Creativity  Art & Design
10               Art & Design  Art & Design
11               Art & Design  Art & Design
12               Art & Design  Art & Design
13               Art & Design  Art & Design
14               Art & Design  Art & Design

### Step 6: Temporal Data Conversion
Converting the `Last Updated` string column into a formal Pandas `datetime` object to allow for time-series analysis and cohort tracking.

In [29]:
# Convert the string dates to datetime objects
data['Last Updated'] = pd.to_datetime(data['Last Updated'])

data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10346 entries, 0 to 10840
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10346 non-null  object
 1   Category        10346 non-null  object
 2   Rating          10346 non-null  float64
 3   Reviews         10346 non-null  object
 4   Size_MB         10346 non-null  float64
 5   Installs        10346 non-null  int64
 6   Type            10346 non-null  object
 7   Price           10346 non-null  float64
 8   Content Rating  10346 non-null  object
 9   Genres          10346 non-null  object
 10  Last Updated    10346 non-null  datetime64[ns]
 11  Current Ver     10346 non-null  object
 12  Android Ver     10346 non-null  object
 13  Primary_Genre   10346 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(1), object(9)
memory usage: 1.2+ MB

In [30]:
# Save cleaned dataset for Phase 2: EDA
data.to_csv('clean_playstore.csv', index = False)